import { Activity, ArrowLeftRight, Boxes, Code2, Gauge, KeyRound, MessageCircleReply, Plus, Search, Settings2 } from 'lucide-react'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

type PageKind = 'providers' | 'logs' | 'tokens' | 'switch' | 'modifiers' | 'auto-reply' | 'concurrency'
const configs: Record<PageKind, { title: string; description: string; icon: typeof Boxes; rows: string[] }> = {
  providers: { title: 'Provider 管理', description: '管理供应商、Base URL 和 Key 资源池', icon: Boxes, rows: ['DeepSeek Official · 2 Base URLs · 3 Keys', 'OpenAI Compatible · 1 Base URL · 2 Keys', 'Anthropic Gateway · 2 Base URLs · 1 Key'] },
  logs: { title: '使用日志', description: '查看请求状态、等待队列和历史记录', icon: Activity, rows: ['GET /v1/responses · deepseek-chat · 2.4s', 'POST /v1/chat/completions · claude-sonnet · 8.1s', 'GET /v1/models · system · 120ms'] },
  tokens: { title: 'API 令牌管理', description: '管理下游 Agent 访问网关的令牌', icon: KeyRound, rows: ['agent-main · 12,400 requests · Active', 'openclaw-local · 8,921 requests · Active', 'test-token · expired · Disabled'] },
  switch: { title: '自动切换规则', description: '定义错误匹配、切换和自动禁用策略', icon: ArrowLeftRight, rows: ['429 / rate limit · 仅切换 · 30s cooldown', '401 / invalid key · 切换并禁用 Key · 10m', 'timeout · 重试 2 次 · 自动探测恢复'] },
  modifiers: { title: '请求修改', description: '独立配置请求头、请求体和响应转换', icon: Code2, rows: ['Reasoning to Think Tags · Response body', 'Provider Compatibility Headers · Request headers', 'Strip Internal Metadata · Response body'] },
  'auto-reply': { title: '自动回复', description: '上游响应缓慢时向下游发送状态提示', icon: MessageCircleReply, rows: ['Slow upstream heartbeat · after 5s · every 3s', 'Queue waiting notice · SSE · once', 'Connection alive · after 10s · every 5s'] },
  concurrency: { title: '并发限制', description: '按 Provider、Base URL 或 Key 配置排队策略', icon: Gauge, rows: ['DeepSeek Official · 8 concurrent · FIFO', 'OpenAI Compatible · 20 concurrent · FIFO', 'Anthropic Gateway · 4 concurrent · priority'] },
}

export function GatewayModulePage({ kind }: { kind: PageKind }) {
  const config = configs[kind]; const Icon = config.icon; const [query, setQuery] = useState('')
  const [active, setActive] = useState<string | null>(null)
  const rows = config.rows.filter((row) => row.toLowerCase().includes(query.toLowerCase()))
  return <div className='min-h-[calc(100vh-3rem)] bg-muted/20 p-6'><div className='mx-auto max-w-6xl'><div className='mb-6 flex items-start justify-between'><div className='flex gap-3'><div className='rounded-xl bg-primary/10 p-3 text-primary'><Icon className='size-6' /></div><div><h1 className='text-2xl font-semibold'>{config.title}</h1><p className='mt-1 text-sm text-muted-foreground'>{config.description}</p></div></div><Button><Plus className='mr-2 size-4' />添加规则</Button></div>{kind === 'logs' && <div className='mb-5 rounded-xl border border-blue-500/30 bg-blue-500/5 p-4'><div className='mb-3 flex items-center gap-2 font-medium'><span className='size-2 animate-pulse rounded-full bg-blue-500' />请求中 <span className='text-xs text-muted-foreground'>3 active · 2 waiting</span></div><div className='grid gap-2 md:grid-cols-3'><div className='rounded-lg bg-background p-3'><p className='text-xs text-muted-foreground'>Receiving upstream</p><p className='mt-1 font-mono text-sm'>deepseek-chat · 12s</p></div><div className='rounded-lg bg-background p-3'><p className='text-xs text-muted-foreground'>Waiting to send</p><p className='mt-1 font-mono text-sm'>claude-sonnet · #2</p></div><div className='rounded-lg bg-background p-3'><p className='text-xs text-muted-foreground'>Streaming</p><p className='mt-1 font-mono text-sm'>gpt-4o · 4.8s</p></div></div></div>}<div className='mb-4 flex max-w-sm items-center gap-2'><Search className='size-4 text-muted-foreground' /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder='搜索...' /></div><div className='space-y-2'>{rows.map((row) => <button type='button' key={row} onClick={() => setActive(row)} className='flex w-full items-center justify-between rounded-xl border bg-background p-4 text-left transition hover:border-primary/50 hover:shadow-sm'><div><p className='font-medium'>{row.split(' · ')[0]}</p><p className='mt-1 text-xs text-muted-foreground'>{row.split(' · ').slice(1).join(' · ')}</p></div><Settings2 className='size-4 text-muted-foreground' /></button>)}</div>{active && <div className='fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4' onClick={() => setActive(null)}><div className='w-full max-w-lg rounded-2xl bg-background p-6 shadow-xl' onClick={(event) => event.stopPropagation()}><h2 className='text-lg font-semibold'>编辑配置</h2><p className='mt-2 text-sm text-muted-foreground'>{active}</p><div className='mt-5 space-y-3'><Input defaultValue={active.split(' · ')[0]} /><Input placeholder='配置说明' /><Button className='w-full' onClick={() => setActive(null)}>保存（Mock）</Button></div></div></div>}</div></div>
}
